### ISSUE TITLE
runtimeError:Errors in loading state_dict for ChatUniViLlamaForCausalLM

### ISSUE THREAD

**Issue by MingfangDeng** [PKU-YuanGroup/Chat-UniVi#10]
![微信图片_20231213151029](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/8c6f0962-462c-46ef-a7d5-c5442ce56972)

I have this problem when I run the video understanding api code. But I see the strict you set is false. Thus, I do not know the reason why I have this problem.
Before this error, I have the following error:
![微信图片1_20231213151222](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/1e48ed1d-56d3-480b-9475-ba65e6b00f64)
I solve this error through downloading the mm_projector.bin in this website https://huggingface.co/liuhaotian/LLaVA-13b-delta-v0/tree/main. Then I place it in a suitable flod.

I guess the first error maybe caused by the unsuitable mm_projector.bin. Can you help me to slove this problem. Thank you very much!

**Comment by jpthu17** [comment]
Firstly, there is no need to provide ```mm_projector.bin``` separately, as the ```mm_projector``` weights are already integrated into the model weights (see [link](https://huggingface.co/Chat-UniVi/Chat-UniVi/blob/34698b194576b4c4339ace247aad5f51fb73e6c0/pytorch_model.bin.index.json#L328-L329)).

I suspect this error may stem from incomplete weight downloads. You can try manually downloading the [files](https://huggingface.co/Chat-UniVi/Chat-UniVi/tree/main) locally:

```
pip install -U huggingface_hub
huggingface-cli download --resume-download Chat-UniVi/Chat-UniVi --local-dir ${model path}
```

then setting the model path as follows:
```
model_path = ${model path}
```

**Comment by MingfangDeng** [comment]
Thank you very much! But I have tried to manualy downloading the files locally, the following is my downloading bin files:
![屏幕截图 2023-12-15 084828](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/bddedc92-743d-448c-a0b4-9afdce4cbc7e)
I use the xftp to transfer the bin files to Server, the size of bin files as the same as the local downloading bin files. I have face the same promblem: no such file mm_projector.bin
![屏幕截图 2023-12-15 085007](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/bab67a48-bf6d-48ca-b2d1-a6b79a45e729)
can you tell me what the problem about this ?

**Comment by jpthu17** [comment]
Did you set parameter ```model_base```? ```model_base``` should be set to None during inference:
```
model_base = None
```

**Comment by MingfangDeng** [comment]
you are right. the model_base should be None. Thank you very much !
