### ISSUE TITLE
Is the clustering algorithm applied during inference?

### ISSUE THREAD

**Issue by notus126** [PKU-YuanGroup/Chat-UniVi#11]
I have read the code but I can not find how the KNN clustering algorithm is applied during inference. I can find how it's applied during training. So is the clustering algorithm applied during inference or not?

**Comment by jpthu17** [comment]
The clustering algorithm also contributes to the inference process, and we have previously tackled an associated [issue](https://github.com/PKU-YuanGroup/Chat-UniVi/issues/3).

If you are interested in the clustering results, you can also print the results of the clustering during the inference phase.
