### ISSUE TITLE
TCBlock is useless

### ISSUE THREAD

**Issue by MarStarck** [PKU-YuanGroup/Chat-UniVi#13]
TCBlock just returns the input dict

**Comment by jpthu17** [comment]
Yes, we found that clustering with trainable parameters actually makes training difficult.
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/53246557/86f088c0-7cd9-4cfd-b1ed-39c5fa2ba6b2)
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/53246557/5a975514-ee91-49ce-8f3e-e9f2a5a9095d)
