### ISSUE TITLE
KeyError: 'COCO2017'

### ISSUE THREAD

**Issue by MingfangDeng** [PKU-YuanGroup/Chat-UniVi#15]
I face the problem when I train this LLM on my own datasets(without coco2017).
![error](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/59062737-289d-4bc1-b4f8-4a904a610bc7)
the follwing operations are made by me:
![训练架构](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/5d9c74f4-70bb-41aa-b77e-fdb52d3ea663)
and the chat.json details are as follow:
![JSON格式](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/3586ab85-fb54-408c-bdb6-9ee4cab73d4c)
And the stage1 of training, I recite it as following:
![stage1](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/89022764/4c8783c9-6aee-4e96-a7d5-0be86acba6a6)
where the model_name or path we downloaded this weight from huggingface: https://huggingface.co/Chat-UniVi/Chat-UniVi/tree/main.
I do not know if I use wrong weight ? or maybe I use ignore the some important issues ? Can you help me ,thank you very much !

**Comment by MingfangDeng** [comment]
sorry, I have solved this problem.

**Comment by Shahad-Mohammed** [comment]
how did you solve it ?
