### ISSUE TITLE
details on COCO based data for pre-training.

### ISSUE THREAD

**Issue by yash0307** [PKU-YuanGroup/Chat-UniVi#17]
Hi,

Thank you for the cool work! Could you share the details on how COCO_CAP, COCO_REC and COCO_REG datasets were obtained?

**Comment by jpthu17** [comment]
These data are generated based on the annotations of the COCO dataset and dialogue templates.

Specifically, the COCO_CAP is generated based on captions of the COCO dataset. COCO_REC and COCO_REG are generated based on ref_coco (A collection of 3 referring expression datasets based on images in the COCO dataset).

The templates and scripts for generating chat data can be found at [Link](https://github.com/PKU-YuanGroup/Chat-UniVi/tree/main/data).

**Comment by yash0307** [comment]
Thanks a lot!
