### ISSUE TITLE
KeyError: 'ChatUniViConfig'

### ISSUE THREAD

**Issue by Juice113** [PKU-YuanGroup/Chat-UniVi#18]
i followed all the steps but got this error when running the inference for image understanding. i downloaded weights from https://huggingface.co/Chat-UniVi/Chat-UniVi/tree/main manually and put them under Chat-UniVi/Chat-UniVi

File "/root/miniconda3/envs/chatunivi2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'ChatUniViConfig'

**Comment by Juice113** [comment]
oh I solved. I successfully ran this inference：I tried to run the inference directly and it downloaded weights by itself, and no bug; I think there is something wrong with my manually downloaded weights from huggingface, I found the second file is 3.8GB which is different from the origin 4.12GB one；

**Comment by jpthu17** [comment]
I apologize for the delayed response. I'm happy that you have resolved this issue.

**Comment by Juice113** [comment]
> I apologize for the delayed response. I'm happy that you have resolved this issue.

It doesn't matter😄
