### ISSUE TITLE
Any plans to implement within HF Transformers?

### ISSUE THREAD

**Issue by athewsey** [PKU-YuanGroup/Chat-UniVi#21]
Hi team, and thanks for publishing!

I've been playing for a few days now to get the model working on Amazon SageMaker endpoints (full disclosure - I work at AWS), and wondered if you had any future plans to try and get the model into the Hugging Face Transformers library itself?

**Comment by jpthu17** [comment]
Hi, thanks for your advice! We will try to get the model into the Hugging Face Transformers library.
