### ISSUE TITLE
about temporal merging

### ISSUE THREAD

**Issue by xxtars** [PKU-YuanGroup/Chat-UniVi#25]
Thank you very much for making your work open source!

I have some questions while reading the paper. How do you ensure that the frames $f^m$ within an event $$ are continuous after clustering frame-level features? Is there any algorithmic constraint for this? I didn't seem to find a related description in the paper or [code](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/53d4b07cdba8085edbfadfd29e42ec5dde113599/ChatUniVi/model/arch.py#L30).

Looking forward to your reply!

**Comment by jpthu17** [comment]
Thank you for bringing up this issue. In our algorithmic, we don't strictly require frames to be adjacent. However, this flexibility can indeed disrupt the video's timing. Do you have any suggestions on how we can address this?
