### ISSUE TITLE
Visualisation code for temporal clustering

### ISSUE THREAD

**Issue by shehanmunasinghe** [PKU-YuanGroup/Chat-UniVi#26]
Could you please provide the visualization code for temporal clustering of videos (i.e. the script used to generate the visualization in https://github.com/PKU-YuanGroup/Chat-UniVi?tab=readme-ov-file#visualization-for-the-video-inputs )

**Comment by jpthu17** [comment]
Sorry, we currently don't have a good video visualization script either. We took a rudimentary approach to visualizing the video, manually recording the position of each event frame, then putting together frames within the same event, and then invoking the [code](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/visualization.py) with a slight adjustment.
