### ISSUE TITLE
v1.5 weights release plan

### ISSUE THREAD

**Issue by HYUNJS** [PKU-YuanGroup/Chat-UniVi#29]
Thank you for your amazing work! May I ask your tentative plan for releasing v1.5 weights whose results are found in below MD? 

https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/TRAIN_AND_VALIDATE_V1.5.md

**Comment by jpthu17** [comment]
Thank you for your interest in our work, and I will upload the weights to HuggingFace within the week.

**Comment by HYUNJS** [comment]
Thank you for your reply!
