### ISSUE TITLE
repalce Vicuna-7B with meta-llama/Meta-Llama-3-8B-Instruct

### ISSUE THREAD

**Issue by mmmwhy** [PKU-YuanGroup/Chat-UniVi#34]
Very thank for yout great job 🙏

I want to replace **Vicuna-7B** with **meta-llama/Meta-Llama-3-8B-Instruct**,   I heard that llama3 performs better, so there may be some gains after replacement.

But I encountered some image dimension related errors during the replacement process, like `indexSelectLargeIndex`.
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/11297491/891b28c2-2992-437f-853d-4d33e7b7eb5a)

my pretrain code is:

> LLM_path set as `Meta-Llama-3-8B-Instruct` path.

```
deepspeed \
--include localhost:0,1,2,3,4,5,6,7 \
--master_port=12345 \
ChatUniVi/train/train_mem.py \
--deepspeed scripts/zero3.json \
--model_name_or_path ${LLM_path} \
--version v1 \
--model_use PRETUNE \
--dataset_use Pretrain \
--vision_tower openai/clip-vit-large-patch14 \
--tune_mm_mlp_adapter True \
--mm_vision_select_layer -2 \
--mm_use_im_start_end False \
--mm_use_im_patch_token False \
--bf16 True \
--output_dir ${stage1_save_path} \
--num_train_epochs 1 \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 4 \
--gradient_accumulation_steps 1 \
--evaluation_strategy "no" \
--save_strategy "steps" \
--save_steps 24000 \
--save_total_limit 1 \
--learning_rate 2e-3 \
--weight_decay 0. \
--warmup_ratio 0.03 \
--lr_scheduler_type "cosine" \
--logging_steps 1 \
--tf32 True \
--model_max_length 2048 \
--gradient_checkpointing True \
--dataloader_num_workers 4 \
--lazy_preprocess True
```

and add this part code for tokenizer

![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/11297491/12695ca8-1c17-4627-b55c-235e70b9a946)

**Comment by mmmwhy** [comment]
can you can share the pre-training code related to llama2, I hope can learn from it😂

**Comment by jpthu17** [comment]
Thank you for sharing the llama3 code. 

Since Vicuna v1.5 is just an instruction-tuned version of llama2, you can directly use Vicuna's code to train on llama2, the only difference is that you can change the [conversation template](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/f63c2478b374417b380af27bc70c693fb1a100a4/ChatUniVi/conversation.py#L222).

**Comment by mmmwhy** [comment]
> Thank you for sharing the llama3 code.
> 
> Since Vicuna v1.5 is just an instruction-tuned version of llama2, you can directly use Vicuna's code to train on llama2, the only difference is that you can change the [conversation template](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/f63c2478b374417b380af27bc70c693fb1a100a4/ChatUniVi/conversation.py#L222).

I find this repo https://github.com/Victorwz/LLaVA-Llama-3 , and i copy some codes from LLaVA-Llama-3 to chat-univi. after that, llama3-8B is starting pretrain 😂

mainly is these two parts:

https://github.com/Victorwz/LLaVA-Llama-3/blob/main/llava/train/train.py#L497
https://github.com/Victorwz/LLaVA-Llama-3/blob/main/llava/conversation.py#264
