### ISSUE TITLE
When will the training codes and model weights of `Chat-UniVi-7B v1.5` be released?

### ISSUE THREAD

**Issue by linhaojia13** [PKU-YuanGroup/Chat-UniVi#39]
In addition, does `Chat-UniVi-7B v1.5` use `clip-vit-large-patch14-336` and `vicuna-7b-v1.5` just as llava-1.5? It seems that the only difference is the usage of `VQAv2` data according to [this](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/TRAIN_AND_VALIDATE_V1.5.md).

**Comment by jpthu17** [comment]
Model weights are available at https://huggingface.co/Chat-UniVi/Chat-UniVi-7B-v1.5/tree/main.

I added all the data from llava v1.5 to the existing training data and also added valley in the pre-training phase. The training script and training data will be updated next week.

**Comment by linhaojia13** [comment]
Thank you very much! You are so kind.
