### ISSUE TITLE
Could you release the trained weights of the Stage-1 Training?

### ISSUE THREAD

**Issue by linhaojia13** [PKU-YuanGroup/Chat-UniVi#41]
The trained connector can help us skip the stage-1 training.

**Comment by jpthu17** [comment]
Of course. The weights of the Stage-1 is [here](https://huggingface.co/Chat-UniVi/Chat-UniVi-7B-v1.5-Stage-1/tree/main).

**Comment by linhaojia13** [comment]
Thank you very much!
