### ISSUE TITLE
Unable to Reproduce Training Process

### ISSUE THREAD

**Issue by Toneyaya** [PKU-YuanGroup/Chat-UniVi#46]
Hello, thank you for your outstanding open-source work! I encountered a problem during the second stage of training when attempting to reproduce the training process. The loss becomes zero across all iterations. This happens regardless of whether I use my trained mm_projector.bin or the weights you released. The loss always drops to zero within the first few iterations. I have followed your instructions precisely to reproduce the training process.

(If anyone has successfully reproduced the training process, let's discuss this issue together.)

![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/53366859/ef902260-6aa3-4c5a-a40f-2d39cc229af2)

**Comment by jpthu17** [comment]
loss is 0, which may be caused by numerical overflow. What kind of GPUs do you use? You can confirm whether the GPU supports bf16. ``` torch.cuda.is_bf16_supported() ``` If it does not support bf16, the value overflow may be caused.

**Comment by annopackage** [comment]
> discuss

same problem here. have you figured it out?

**Comment by Toneyaya** [comment]
Yes. Thanks for your help!
