### ISSUE TITLE
Is it a mistake to get patch_num_h from w?

### ISSUE THREAD

**Issue by 21makunyang** [PKU-YuanGroup/Chat-UniVi#48]
Hi, is it a mistake to get patch_num_h from w at line 33 in Chat-UniVi/visualization.py? 
``` 
h, w, _ = img.shape

patch_num_h, patch_num_w = w // patch_size, w // patch_size
```
Is it supposed to be like this?
`patch_num_h, patch_num_w = h // patch_size, w // patch_size`

**Comment by jpthu17** [comment]
Thanks for pointing out the bug, I've fixed it.
