### ISSUE TITLE
Downloading the ActivityNet (Zero Shot) Dataset

### ISSUE THREAD

**Issue by Backdrop9019** [PKU-YuanGroup/Chat-UniVi#50]
Hello, thank you for sharing the excellent code.

I am trying to download the Activitynet_Zero_Shot_QA dataset, but it seems that this data is not available on Hugging Face. Additionally, I attempted to download it using Baidu Disk, but as a foreigner, I am restricted from signing up for Baidu.

Could you please share this data through a public platform such as Google Drive? Alternatively, I would greatly appreciate it if you could provide an alternative way to download the data.

Thank you very much.

**Comment by jpthu17** [comment]
You can download Activitynet_Zero_Shot_QA dataset from https://mbzuaiac-my.sharepoint.com/personal/hanoona_bangalath_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FData%2FActivityNet%5FTest%2D1%2D3%5Fvideos%2Ezip&parent=%2Fpersonal%2Fhanoona%5Fbangalath%5Fmbzuai%5Fac%5Fae%2FDocuments%2FVideo%2DChatGPT%2FData%5FCode%5FModel%5FRelease%2FData&ga=1

**Comment by Backdrop9019** [comment]
Thank @jpthu17  for the prompt response. However, the link you provided is also inaccessible due to the following error: AADSTS90072: User account 'backdrop9019@gmail.com' from identity provider 'live.com' does not exist in tenant 'Mohamed Bin Zayed University of Artificial Intelligence' and cannot access the application '00000003-0000-0ff1-ce00-000000000000'(Office 365 SharePoint Online) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account"

Maybe I cannot access it because im an external user :(

**Comment by Backdrop9019** [comment]
“Oh, I resolved it. Thank you, I will close the issue.“​⬤
