### ISSUE TITLE
Why `image_aspect_ratio` is set to `square` rather than `pad`

### ISSUE THREAD

**Issue by linhaojia13** [PKU-YuanGroup/Chat-UniVi#51]
1. The object in the image will be streched. It is difficult to determine whether this will lead to negative impacts. Why do you  choose such a different setting.
2. In addition, the bounding box in the llava-mixed data will be incorrect.

**Comment by jpthu17** [comment]
You're correct. It was an oversight during the training of the v1.5 version, and I believe that configuring it similarly to Llava could potentially enhance the results.
