### ISSUE TITLE
Does dynamic visual token need position embedding?

### ISSUE THREAD

**Issue by beitong95** [PKU-YuanGroup/Chat-UniVi#57]

**Comment by beitong95** [comment]
And also how many clusters are used in the Single-scale test in Table G.

**Comment by jpthu17** [comment]
For Spatial Merging, I think additional position encoding is unnecessary since the tokens have already added position encoding in the ViT. However, for Temporal Merging, incorporating position encoding might be beneficial, and this could be a valuable direction for future works.

**Comment by jpthu17** [comment]
For the Single-scale test in Table G, only the first step clustering is included.
![image](https://github.com/user-attachments/assets/90a0bcd3-bbbe-4213-a1e4-535c46c0e101)

**Comment by beitong95** [comment]
Thank you so much!
