### ISSUE TITLE
Aggregation Method

### ISSUE THREAD

**Issue by Solo4working** [PKU-YuanGroup/Chat-UniVi#63]
Thanks for your nice work, but I'm curious if there's been any experimentation with traditional aggregation methods? Like Conv downsampling or MeanPooling/MaxPooling, what is the effect?

**Comment by jpthu17** [comment]
We haven't tried these simple aggregation methods, but there has been work [2404.16994](https://arxiv.org/pdf/2404.16994) using pooling to aggregate video tokens

**Comment by Solo4working** [comment]
> We haven't tried these simple aggregation methods, but there has been work [2404.16994](https://arxiv.org/pdf/2404.16994) using pooling to aggregate video tokens

Thanks for your quick reply! I will check it out.
