### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by pd162** [PKU-YuanGroup/Chat-UniVi#7]
Thanks for your outstanding work! And I have a question about the visualization of paper. I noticed that dynamic visual tokens of Fig. 1 in the paper, and I also find corresponding core funtion [`vis_token` in TCFormer](https://github.com/zengwang430521/TCFormer/blob/aaff2b701e3ec132306245ed52f6c9b1f8667a46/tcformer_module/tcformer_utils.py#L499), but I cannot reproduce this picture. I want to ask to visualize dynamic tokens in detail. It would be even better if visualization scripts could be open-source!

**Comment by jpthu17** [comment]
I have released the visualization script. You can locate it in [VISUALIZATION.md](https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/VISUALIZATION.md).

**Comment by pd162** [comment]
Thx! Looks great!
