### ISSUE TITLE
Question regarding GPT scores for video comprehension

### ISSUE THREAD

**Issue by yuu2704** [PKU-YuanGroup/Chat-UniVi#9]
Thanks for the great work. And I have a question about the GPT scores for video comprehension.

I evaluated the GPT score for video comprehension using the evaluation code you published and the hugginface 7B model ('Chat-UniVi/Chat-UniVi') that you also published, and I got a very low score of 47.7 in the temporal evaluation.
I don't think this means that it is a swing in generation or GPT evaluation, as I have tried several times, but can you think of any cause?

I apologize for asking such a vague question, but I hope you can help me.

**Comment by cv-learner** [comment]
@yuu2704 Hi, did you conduct the temporal evaluation with `ChatUniVi/eval/questions/video_qa/generic_qa.json` or `ChatUniVi/eval/questions/video_qa/temporal_qa.json`?

**Comment by jpthu17** [comment]
We've revised the temporal evaluation performance of video understanding, resulting in an actual model performance of 47.9 instead of the previously stated 57.8. 

We sincerely apologize for any inconvenience our oversight may have caused you.
